name: astronomy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  downloads_path_provider_28: ^0.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^8.1.1+2
  flutter_mobx: ^2.0.2
  fluttertoast: ^8.0.8
  fpdart: ^0.0.9
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_gallery_saver: ^1.6.9
  injectable: ^1.4.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  shimmer: ^2.0.0
  social_share: ^2.1.1
  url_launcher: ^6.0.10

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  mobx_codegen: ^2.0.2
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
