name: astronomy
description: A project that uses NASA's API to show awesome pictures of the universe each day.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.1.0
  dio: ^4.0.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^12.0.4
  mobx: ^2.1.3
  flutter_mobx: ^2.0.2
  fluttertoast: ^8.0.8
  fpdart: ^0.4.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.6.9
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.2
  permission_handler: ^10.2.0
  shimmer: ^2.0.0
  social_share: ^2.1.1
  url_launcher: ^6.0.10
  translator: ^0.1.7
  async: ^2.6.1
  showcaseview: ^2.0.0+1
  animations: ^2.0.1
  animated_check: ^1.0.4
  flutter_feather_icons: ^2.0.0+1
  chopper: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  hive_generator: ^1.1.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  mobx_codegen: ^2.0.2
  mocktail: ^0.3.0
  chopper_generator: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env
