name: astronomy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fpdart: ^0.0.9
  http: ^0.13.3
  google_fonts: ^2.1.0
  injectable: ^1.4.1
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  json_annotation: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  mobx_codegen: ^2.0.2
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/